### ISSUE TITLE
Vyos configuration issue

### ISSUE THREAD

**Issue by al-pankov** [Zen3515/homeassistant-vyos-router#5]
Hello!

Something strange in work of your integration.
Script got data from vyos, but can't parse it.

Please, check my config file and debug log of homeassistant.
[home-assistant_vyos_2024-02-01T13-31-05.885Z.log](https://github.com/Zen3515/homeassistant-vyos-router/files/14127137/home-assistant_vyos_2024-02-01T13-31-05.885Z.log)
[vyos-config-dhcp.txt](https://github.com/Zen3515/homeassistant-vyos-router/files/14127138/vyos-config-dhcp.txt)

**Comment by Zen3515** [comment]
Hello, this issue should be fixed in [2024.2.1](https://github.com/Zen3515/homeassistant-vyos-router/releases/tag/2024.2.1).
Please give it a try and let me know.

**Comment by al-pankov** [comment]
It's OK, now.
Thank you!
